/**
 * A2UI (Agent-to-User Interface) Component Definitions
 * 
 * Standardized schema for dynamic UI components generated by the agent.
 * These are intended to be rendered in the Feedback Studio or as MCP Artifacts.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const COMPONENT_TYPES = {
  REASONING_TRACE: 'reasoning-trace',   // Graph/List showing how dots were connected
  RULE_PROPOSAL: 'rule-proposal',       // Interactive card to approve/refine a rule
  CONFLICT_VETO: 'conflict-veto',       // UI to resolve contradicting memories
  METRIC_DYNAMIC: 'metric-dynamic'      // Real-time custom metrics based on current task
};

/**
 * Generate a Reasoning Trace component (A2UI)
 * @param {string} summary - High-level synthesis
 * @param {Array} sources - List of source logs/memories
 * @param {Array} connections - Semantic links found
 */
function createReasoningTrace(summary, sources, connections) {
  return {
    type: COMPONENT_TYPES.REASONING_TRACE,
    version: '1.0.0',
    data: {
      summary,
      sources: sources.map(s => ({
        id: s.id,
        text: s.context || s.content,
        signal: s.signal || 'neutral'
      })),
      graph: connections.map(c => ({
        from: c.sourceId,
        to: c.targetId,
        label: c.relation
      }))
    },
    actions: [
      { id: 'view-logs', label: 'View Raw Logs', type: 'primary' }
    ]
  };
}

/**
 * Generate a Rule Proposal component (A2UI)
 */
function createRuleProposal(pattern, suggestedRule, severity) {
  return {
    type: COMPONENT_TYPES.RULE_PROPOSAL,
    version: '1.0.0',
    data: {
      pattern,
      suggestedRule,
      severity
    },
    actions: [
      { id: 'approve', label: 'Approve ALWAYS/NEVER', type: 'success' },
      { id: 'refine', label: 'Tweak Wording', type: 'secondary' },
      { id: 'veto', label: 'Veto Rule', type: 'danger' }
    ]
  };
}

module.exports = {
  COMPONENT_TYPES,
  createReasoningTrace,
  createRuleProposal
};
